### ISSUE TITLE
[FreeLive] Live2D Inc.: Regarding violation against our EULA 

### ISSUE THREAD

**Issue by itoh-at-live2d-com** [UlyssesWu/D2Evil#1]
@UlyssesWu 

I'm Live2D Inc. staff in charge of legal issue and user support.

We see that the content of your GitHub Repository is a clear violation against our EULA.
https://github.com/UlyssesWu/FreeLive

It violates the No Reverse Engineering clause in the following two EULAs.

https://www.live2d.com/eula/live2D-editor-software-license-agreement_en.html
[ Software License Agreement ]
5.1.2 No Reverse Engineering
The Customer may not reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code of the Software except in case which the Customer performs modifications of the Software for its own use and reverse engineering for debugging such modifications.

https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_en.html
[ Live2D Proprietary Software License Agreement ]
6.4 No Reverse Engineering
The Customer may not reverse engineer, decompile, disassemble, or otherwise attempt to discover the Source Code of the Software.

We are writing to ask you to stop providing this Repository on your GitHub account, delete any content, cease any activity which violates our EULA as soon as possible.

**Comment by UlyssesWu** [comment]
I have removed the UlyssesWu/FreeLive repo. Now waiting for any explanation about my doubts.

**Comment by itoh-at-live2d-com** [comment]
@UlyssesWu 

We understand that the content of your repository is "a simple analysis of the file formats from your open-source repos from https://github.com/Live2D".

Please be advised that our repositories in https://github.com/Live2D are not open-source. Some components are provided with Live2D Open Software License, but this does not mean that they are open-source:
https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html

Our EULA expressly restricts "discovering the source code". We observed that your repository contains what would not be able to obtain without "discovering" the source code of software provided with Live2D Proprietary Software License Agreement:
https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_en.html

**Comment by UlyssesWu** [comment]
> repositories in https://github.com/Live2D are not open-source

Oh, I understand, but that's still ok for me, since they are no more than name references for this repo. As you can see, I didn't borrow any code from them anyway.

> your repository contains what would not be able to obtain without "discovering" the source code of software

For me, "coding" is something turns "unable" to "able". People won't believe it's possible to get source code for binaries before the first decompiler comes out. People won't believe anything can be analyzed and imitated before deep-learning comes out.

Anyway, this repo should be fine for you since from now on there are no code here.

**Comment by UlyssesWu** [comment]
![l2d-star](https://user-images.githubusercontent.com/4312781/67409261-e7b50d00-f5ec-11e9-8b67-1f13c0ad48aa.png)

![l2d-star-2](https://user-images.githubusercontent.com/4312781/67409319-fef3fa80-f5ec-11e9-9b24-18ceb50bd3cd.png)

Thank you very much for starring FreeLive. It has been a month since you watched that repository and you [starred](https://help.github.com/en/github/getting-started-with-github/saving-repositories-with-stars) it rather than took it down. 

> Starring a repository also shows appreciation to the repository maintainer for their work. - Saving repositories with stars, GitHub Help

It seems that either [you](https://www.wantedly.com/users/84696775) (as the developer from Live2D Inc.) or github has believed there is no "legal issue" in my code - as I always believed.
I won't mind sharing more codes here, later. Thank you.

**Comment by marcussacana** [comment]
What I saw here?
Uly, after this what the key differences around the old FreeLive and D2Evil?
I'm really sad, you don't know how much I admired this project, I searched today to use it and got this.
whatever, Uly, I'm trying open a moc file that I dumped from a game to use in your Wallpaper Engine app, if possible, you can give me a help? my discord: Marcus André#0956

**Comment by skyrina** [comment]
> @UlyssesWu
> 
> I'm Live2D Inc. staff in charge of legal issue and user support.
> 
> We see that the content of your GitHub Repository is a clear violation against our EULA. https://github.com/UlyssesWu/FreeLive
> 
> It violates the No Reverse Engineering clause in the following two EULAs.
> 
> https://www.live2d.com/eula/live2D-editor-software-license-agreement_en.html [ Software License Agreement ] 5.1.2 No Reverse Engineering The Customer may not reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code of the Software except in case which the Customer performs modifications of the Software for its own use and reverse engineering for debugging such modifications.
> 
> https://www.live2d.com/eula/live2d-proprietary-software-license-agreement_en.html [ Live2D Proprietary Software License Agreement ] 6.4 No Reverse Engineering The Customer may not reverse engineer, decompile, disassemble, or otherwise attempt to discover the Source Code of the Software.
> 
> We are writing to ask you to stop providing this Repository on your GitHub account, delete any content, cease any activity which violates our EULA as soon as possible.

🤓
