### ISSUE TITLE
Open source MOC3 to CMO3 converter?

### ISSUE THREAD

**Issue by Ronsor** [UlyssesWu/D2Evil#6]
While you had said you were not likely to release the code, and Live2D had stirred a bit of drama a few years ago, at this point both MOC3 and CMO3 formats have been publicly documented with at least one working parser for each. I do not think there would be much trouble now.

**Comment by UlyssesWu** [comment]
I'm afraid I never said I'd open source this piece of code. The moc3 code was open-sourced from beginning but the cmo3 code is not. Considering the time and effort I have spent on that (much more than moc3) it's not an easy decision for me to open-source that for now. 

If you want to prove you can do some **real original work** (better than "[a deeply flawed and potentially unfixable piece of software](https://undeleted.ronsor.com/live2d-a-security-trainwreck/)") other than that [unsuccessful](https://github.com/OpenL2D/moc3ingbird/issues/2) "CVE", go ahead and make an open-source one by yourself. However, it's obvious that your "[100% legal, FOSS reimplementation of Cubism Core](https://github.com/OpenL2D/PurismCore)" won't be able to clone cmo3 implementation because with basic inspection of cmo3 you'd have realized it's just a simple serialization of Java objects, while your OpenL2D - if it's not a simple clone of [inochi](https://github.com/Inochi2D/inochi2d) - was not written in Java but D (just like inochi). 

And I think you already know you don't have to clone cmo3 if you really want to make your L2D system. You can make your own project format (if it's not `.inx`), as long as you can compile the project file to a moc3 file. I have no idea why you'd be interested in moc3 to cmo3. Try finding another "CVE"? You won't need this, either.

**Comment by Ronsor** [comment]
Fair enough. I have had a peek at the `main.xml` and noticed the Java objects, although they shouldn't be a significant hurdle. As an example, being serialized Python objects, there are JS parsers for Python's pickle format. Up until now I had only focused on the MOC3 loading, and not CMO3. 

I'm honestly more interested in converting CMO3 (and possibly exported MOC3 files) to a more sane project format I'm in the process of defining. 

Also, the OpenL2D code is completely original, not copied from Inochi. It's also very incomplete; I sort of want to start over now that I understand the formats better.

**Comment by UlyssesWu** [comment]
> the OpenL2D code is completely original, not copied from Inochi. It's also very incomplete; I sort of want to start over now that I understand the formats better.

That's right, since the "OpenL2D" are ONLY some model format code till now, no one would expect to see such code in Inochi. It's a nice timing for you to start over, since if you continue with those code you may have to start copying from Inochi. No? Then tell me a convincing reason why you choose D - a language you never commited before. You already know that a JVM language will be much easier to handle moc3 or cmo3.

---
> [*almost certainly* possible to execute arbitrary code](https://github.com/OpenL2D/moc3ingbird/blame/23a08552f121aaf9a5ddc629405a3cc272657cc2/README.md#L29)  --- 2023-03-03
> [bad actors could *easily* take advantage of these vulnerabilities in order to deploy spyware on unsuspecting users’ computers](https://undeleted.ronsor.com/live2d-a-security-trainwreck/)  --- 2023-03-03
> [You should support free, open alternatives to Live2D’s software](https://undeleted.ronsor.com/live2d-a-security-trainwreck/)  --- 2023-03-03 (Yeah, like something with a few lines of *original* parsing code?)
> [*As of now*, I have not found a way ... however, code execution *may still* be possible](https://github.com/OpenL2D/moc3ingbird/blame/23a08552f121aaf9a5ddc629405a3cc272657cc2/README.md#L31-L33)  --- 2023-03-06 (wow, isn't it *easily*? Have you found a way after another 5 months?)
> [they *shouldn't* be a significant hurdle](https://github.com/UlyssesWu/D2Evil/issues/6#issuecomment-1685604421)   --- 2023-08-21

Trash Talk is cheap, show me the result. Even a baby can crack a toy, that doesn't mean he/she can make a better one.

**Comment by LunaTheFoxgirl** [comment]
Just want to chime in and say that I'd prefer if you don't use Inochi2D to try to roast or demotivate people from pursuing projects. @UlyssesWu 

I don't personally have any interest in Live2D or implementing that format, but demotivating people before they even get something off the ground is imho bad form.

**Comment by UlyssesWu** [comment]
@LunaTheFoxgirl 
I checked my words, I believe I didn't say any bad words about Inochi2D. I just mentioned it, because he mentioned it in his "report".

Ronsor's "CVE" was drawing everyone's attention in the past, even the L2D official have to released a patch to "fix" it. Just because his words like "almost _certainly_ possible to execute arbitrary code".
But is it real? He couldn't prove it to be actually exploitable till now - even after this discussion. If he cannot prove it, he was just using a fake "CVE" trying to get famous.
That's why I, and perhaps others like https://github.com/OpenL2D/moc3ingbird/issues/2 , feel unhappy. And that's why I don't believe he would actually create a "[100% legal, FOSS reimplementation of Cubism Core](https://github.com/OpenL2D/PurismCore)", **because he had made a gimmick before and never achieve it actually, and now he is making another one.**

If you don't like my words, I'd suggest you should read his words before mine. For example this:
"[a deeply flawed and potentially unfixable piece of software](https://undeleted.ronsor.com/live2d-a-security-trainwreck/)". 
Keep in mind that in this article he also mentioned Inochi2D.
Should I say, I'd prefer if he didn't use Inochi2D to try to roast or demotivate the L2D devs from pursuing projects? 🤣

**Comment by LunaTheFoxgirl** [comment]
I very much agree that the CVE was both silly in its presentation, functionality and the way Ronsor "disclosed" it was inappropriate.

OTOH, you can be nicer about that.

**Comment by UlyssesWu** [comment]
Why should I "be nicer" while he never admits about the fact of his "CVE" and that "report" with so many exaggerated descriptions is still there without corrections, misleading more people every day? 
When you ask me to "be nice" to someone who posts fake CVEs, isn't it **unfair** for real security researchers? 
I would "be nice" for honest mistakes. But never for gimmick. Don't be sanctimonious. For justice!

**Comment by v1ckxy** [comment]
So after all of this noise and fuzz, nobody released a decompiler.
A lot of talk, one complaining about security but nothing shown, the company in a typical jway crying _"please don't decompile our format mimimi it's all ours"_ -as any kind of law outside japan will protect that- and, after all this time... _that's all folks_

In the end, nobody moved a finger.

funny and ironic in equal parts, tbh.

**Comment by kurahaupo** [comment]
> Ronsor's "CVE" was drawing everyone's attention in the past, even the L2D official have to released a patch to "fix" it. Just because his words like "almost _certainly_ possible to execute arbitrary code". But is it real? He couldn't prove it to be actually exploitable till now - even after this discussion. If he cannot prove it, he was just using a fake "CVE" trying to get famous.

I initially read the CVE, and then came here. And I followed your link to his longer explanation.

The CVE is certainly one of the most inflammatorily-worded ones I've ever seen. But that does not necessarily mean it's wrong, nor does it imply bad faith. Rather, it just points to extreme frustration (and perhaps a little immaturity).

That explanation is a model of clarity, and absolutely proves his case: the software had a very serious security weakness that - with only a few minor coincidences -would have been exploitable.

It is perfectly possible to _prove_ that something is exploitable, without _writing_ an actual exploit. I draw your attention to this phrase:

* “a rogue MOC3 file could easily instruct Cubism Core to overwrite any memory within ~2 GiB of where the MOC3 data is located”

If true, that would mean that the software was absolutely-for-sure exploitable on any 32-bit system. This much is _old_ common knowledge among security researchers and criminal hackers, and after the briefest consideration, is blindingly obvious to anyone else who has even a basic understanding of CPU instructions: if you can write instructions, you can do anything.

If not true, why else did it crash when trying to load a corrupted file?

On systems with wider addresses, the difficulty of exploitation would depend on whether the MOC3 data buffer is in the stack, in allocated memory, or among the static variables; and perhaps it might not be possible, but that would be dumb luck, depending on flukes in code that has nothing to do with loading MOC3 files.

Normally address randomisation offers a degree of protection against memory overwrite exploits, but in this case it uses relative offsets, which will obviate even that little protection.

That's of course not the only thing needed to build an exploit:
* a code vector, either
  * having a memory area that is both writable and executable; or
  * finding code snippets in a typical compiled version that would allow return-oriented-programming to perform useful operations; and
* mapping where other objects are in memory, especially pointers that could be co-opted to write into other memory zones.

In any large project, the chance of _not_ finding enough useful code snippets is basically zero; you'll always find enough to do _something_ interesting.

Mapping objects in memory only takes reading the source code, or spending time with a debugger; there's no chance to prevent it, so your only hope is to make it too expensive for everyone to bother.

Demanding delivery of a proof-of-concept exploit is unwise, since that means all the hard work has been done for the hackers, and it would take them only days after that to craft a real malware exploit.

I don't know whether it's been fixed since. I would certainly hope so, but I wouldn't trust that until there is some acknowledgement of the original flaw, and how they've mitigated it.

**Comment by UlyssesWu** [comment]
> I don't know whether it's been fixed since.

They have fixed this *bug*. I think it's just about adding a boundary check. The "CVE" is no more than that.

> Demanding delivery of a proof-of-concept exploit is unwise, since that means all the hard work has been done for the hackers, and it would take them only days after that to craft a real malware exploit.

1. Since they already fixed that, it should be definitely okay to release a PoC. One have to prove his "CVE" is a vulnerability. Even before the fix, he should've proved that. He didn't have to publish the code, a video to demostrate the popup of shell / calculator etc. would be convincing.
2. [bad actors could **easily** take advantage of these vulnerabilities in order to deploy spyware on unsuspecting users’ computers](https://undeleted.ronsor.com/live2d-a-security-trainwreck/)  --- I'd repeat my words: He said **easily**. While you're talking about "**hard** work has been done for the hackers", he already said it's easy for hackers. If he cannot show us an EASY PoC, he was just lying.

Anyway, thank you for your lengthy comment. It will help people understand the facts from more perspectives. @kurahaupo

**Comment by kurahaupo** [comment]
Sorry if I've caused some confusion; a task can be "hard" relative to some other task, while still being "easy" overall, especially to someone who's well practised at it.

Those two statements do NOT contradict each other.

**Comment by UlyssesWu** [comment]
If you're a "well practised", I hope you can prove it with a PoC --- as I've said, it won't be harmful since they've fixed it in new versions.

If you're not, I'm afraid you have some kind of unrealistic imagination about "hackers", just like him.

**Comment by kurahaupo** [comment]
I get it, there are “nuisance” CVEs written by people with no clue, sometimes motivated by wanting  to make a name for themselves. However those CVEs are really obvious from their lack of rigour, and that certainly can't be said about this issue - once you get past the cussing.

> I think it's just about adding a boundary check. The "CVE" is no more than that.

You seem to be implying that a missing boundary check is too frivolous to warrant a CVE.

That's not how the CVE system works.

A bug involving a missing boundary check when processing user-supplied data is _absolutely_ grounds for a CVE. The "V" stands for "vulnerability", and there's no question that there's a vulnerability, whether or not a PoC exploit can be written today.

> > Demanding delivery of a proof-of-concept exploit is unwise, 

Aiding an attacker is only one reason. Not trashing your own reputation is another. I would encourage you to reconsider before doubling down.

> If he cannot show us an EASY PoC, he was just lying.

Making ad-hominem attacks is usually a last resort when one has no better excuses.
Combining that with a logical fallacy (such as the excluded middle in this case) is a sure fire way to make readers suspicious of one's motives.

There are many reasons why a reporter might _not_ provide a PoC for a real vulnerability, including;
* they aren't themselves hackers and don't have the skills (but they're good at debugging crashes, such as buffer overruns);
* they may have discovered the vulnerability in the course of their employment, and even written a PoC, but their employer won't permit it to be published - or to be recorded while running (ruling out a video or similar);
* they live somewhere without legal protection for responsible disclosure, and “facilitating illegal acts” is itself a crime that could result in jail time;
* they're not being paid for the time it would take to write one (and don't have enough spare time to donate);
* disclosure might _actually_ aid attackers (not applicable since it's been patched, but included for completeness);
* they don't see why they need to spend any _more_ time on someone else's bug, when it's already been proven.

> I'd repeat my words:

And I will repeat mine: it is perfectly possible to _prove_ that something is exploitable, _without_ writing an actual exploit.

And that's an over-statement: a CVE only requires proof that there's a vulnerability, not that an exploit is practicable.

One of the score factors is exactly that: how practicable it is to exploit the vulnerability. CVEs are recorded this way precisely because that score can change as the environment evolves.

Behind all of this seems to be a tacit assumption that lack of a PoC equates to "no proof". That's simply not what "proof" means.

1. We know from decades of painful past experience that bounds check failures can be leveraged to allow arbitrary code execution in the vast majority of cases, even with mitigation strategies such as address space randomisation, and to deny service in _all_ cases (by crashing).
2. Given that a patch has been applied to enforce bounding checks in code that reads user-supplied files, that implies that one or more failures did, in fact, exist.
3. Taken together (1) and (2) constitute proof that a CVE-worthy fault existed.

Which of these statements do you find unconvincing?

Why should anyone waste time and effort writing a PoC for something that's already proven?

**Comment by UlyssesWu** [comment]
He proved it leads to a crash. He didn't prove it leads to an "exploit". Even if he, or you, write these theoretical possibilites, they are NOT **obiviously** leading to his conclusion like "[almost certainly possible to execute arbitrary code](https://github.com/OpenL2D/moc3ingbird/blame/23a08552f121aaf9a5ddc629405a3cc272657cc2/README.md#L29)". I'd say, that's a misleading.

Yes, you can have examples for other CVEs not showing PoC. But I didn't see them misleading people like this. For this one, he writed exaggerated statements (_easily, almost certainly_ etc. there're full of such statements in that article), and I am asking a prove for **this**. 

If his article is about a CVE to crash the Editor, I will not say a word, while I don't think it's necessary for a CVE either. 
But since he was confidently writing like this without a prove or correction even after so many months, I'll start doubting his intentions.

**Comment by v1ckxy** [comment]
Ok, but the converter it is going to be released or not? 😂😂😂
